# Generated by Django 6.0 on 2026-01-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0005_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('raw', 'Raw Material'), ('consumable', 'Consumable'), ('finished', 'Finished Goods')], max_length=20)),
                ('uom', models.CharField(max_length=20)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendors', models.ManyToManyField(blank=True, to='finance.vendor')),
            ],
        ),
    ]
