# Generated by Django 6.0 on 2026-01-19 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualityinspection',
            options={'ordering': ['-inspection_date']},
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='status',
            field=models.CharField(choices=[('pending_qc', 'Pending QC'), ('qc_in_progress', 'QC In Progress'), ('qc_passed', 'QC Passed'), ('qc_rejected', 'QC Rejected'), ('grn_created', 'GRN Created'), ('cancelled', 'Cancelled')], default='pending_qc', max_length=20),
        ),
        migrations.AlterField(
            model_name='grn',
            name='gate_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.gateentry'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='gate_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inventory.gateentry'),
        ),
    ]
