# Generated by Django 6.0 on 2026-01-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_qualityinspection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='quality_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.qualityinspection'),
        ),
        migrations.AlterField(
            model_name='grn',
            name='gate_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.gateentry'),
        ),
    ]
