# Generated by Django 6.0 on 2026-01-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_vendor'),
        ('inventory', '0003_grn_quality_inspection_alter_grn_gate_entry'),
        ('organizations', '0019_alter_organizationuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('raw', 'Raw Material'), ('consumable', 'Consumable'), ('finished', 'Finished Goods')], default='raw', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.CharField(help_text='Unit of Measurement (e.g. Kg, Nos, Liter)', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='items', to='finance.vendor'),
        ),
    ]
