# Generated by Django 6.0 on 2026-01-23 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_options_item_organization_item_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grn',
            options={'ordering': ['-received_date'], 'verbose_name': 'Goods Received Note', 'verbose_name_plural': 'Goods Received Notes'},
        ),
        migrations.AlterModelOptions(
            name='grnitem',
            options={'verbose_name': 'GRN Item', 'verbose_name_plural': 'GRN Items'},
        ),
        migrations.AddField(
            model_name='grn',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when this GRN was approved', null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this GRN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grns', to=settings.AUTH_USER_MODEL),
        ),
    ]
