# Generated by Django 6.0 on 2026-03-18 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='description',
        ),
        migrations.AddField(
            model_name='machine',
            name='default_queue_time_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours job waits before processing', max_digits=6),
        ),
        migrations.AddField(
            model_name='machine',
            name='efficiency_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Efficiency % (new machine=95%, old=70%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='machine',
            name='hourly_labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per hour for operator', max_digits=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='hourly_overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per hour for electricity, maintenance', max_digits=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenance_status',
            field=models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('breakdown', 'Breakdown')], default='operational', help_text='Current operational status', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='setup_time_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard setup/changeover time in hours', max_digits=6),
        ),
        migrations.AddField(
            model_name='machine',
            name='utilization_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Utilization % (85% = 15% planned downtime)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='machine',
            name='work_center_type',
            field=models.CharField(choices=[('machine', 'Machine Tool'), ('assembly', 'Assembly Station'), ('inspection', 'Quality Station'), ('labor', 'Manual Work')], default='machine', help_text='Type determines scheduling logic', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='capacity_per_day_hours',
            field=models.PositiveIntegerField(default=8, help_text='Hours available per day (e.g., 8 for single shift, 16 for double)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-1c2303c9', help_text='Unique machine code', max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for production planning'),
        ),
    ]
