# Generated by Django 6.0 on 2026-03-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0029_merge_20260110_1302'),
        ('inventory', '0006_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps_hr.department'),
        ),
    ]
