# Generated by Django 6.0 on 2026-03-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockledger_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-ef4c19ae', help_text='Unique machine code', max_length=50),
        ),
    ]
