# Generated by Django 6.0 on 2026-03-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_machine_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes or description about the machine', null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-9fcf161a', help_text='Unique machine code', max_length=50),
        ),
    ]
