# Generated by Django 6.0 on 2026-03-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_machine_description_alter_machine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-8f5a535b', help_text='Unique machine code', max_length=50),
        ),
    ]
