# Generated by Django 6.0 on 2026-03-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_machine_code'),
        ('inventory', '0009_alter_machine_code'),
    ]

    operations = [
    ]
