# Generated by Django 6.0 on 2026-03-23 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_0008_alter_machine_code_0009_alter_machine_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('purchase', 'Purchase Item'), ('production', 'Production Item')], default='purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-68334d10', help_text='Unique machine code', max_length=50),
        ),
        migrations.CreateModel(
            name='ItemDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity required to produce parent item', max_digits=10)),
                ('child_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='inventory.item')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.item')),
            ],
            options={
                'unique_together': {('parent_item', 'child_item')},
            },
        ),
    ]
