# Generated by Django 6.0 on 2026-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_item_type_alter_machine_code_itemdependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-37e88a72', help_text='Unique machine code', max_length=50),
        ),
    ]
