# Generated by Django 6.0 on 2026-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_machine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-2bfd0ce3', help_text='Unique machine code', max_length=50),
        ),
    ]
