# Generated by Django 6.0 on 2026-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_vendorpayment_vendor_purchaseorder_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-de3447c9', help_text='Unique machine code', max_length=50),
        ),
    ]
