# Generated by Django 6.0 on 2026-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_machine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-3bb69266', help_text='Unique machine code', max_length=50),
        ),
    ]
