# Generated by Django 6.0 on 2026-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_machine_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-9cd0f78c', help_text='Unique machine code', max_length=50),
        ),
    ]
