# Generated by Django 6.0 on 2026-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_vendorinvoice_paid_amount_alter_machine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-4beccaf6', help_text='Unique machine code', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
