# Generated by Django 6.0 on 2026-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_machine_code_dispatch_dispatchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-a02f4734', help_text='Unique machine code', max_length=50),
        ),
    ]
