# Generated by Django 6.0 on 2026-04-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_dispatch_created_at_alter_machine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-46de8659', help_text='Unique machine code', max_length=50),
        ),
    ]
