# Generated by Django 6.0 on 2026-04-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_machine_code_purchasereturn_purchasereturnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-262a81eb', help_text='Unique machine code', max_length=50),
        ),
        migrations.CreateModel(
            name='VendorInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.vendorinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
        ),
    ]
