# Generated by Django 6.0 on 2026-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_machine_code_vendorinvoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-00b9fc0b', help_text='Unique machine code', max_length=50),
        ),
    ]
