# Generated by Django 6.0 on 2026-06-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_machine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-3812d262', help_text='Unique machine code', max_length=50),
        ),
    ]
