# Generated by Django 6.0 on 2026-07-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_machine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(default='MACHINE-3688cb92', help_text='Unique machine code', max_length=50),
        ),
    ]
