# Generated by Django 5.2.8 on 2025-11-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationmodule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='title',
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='employee_docs/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.organizationuser'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.organizationuser'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.organization'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.erpmodule'),
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.organization'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.organizationuser'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.organization'),
        ),
    ]
