# Generated by Django 5.2.8 on 2025-12-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0003_employeeinvite'),
        ('organizations', '0004_organization_code_organizationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinvite',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
