# Generated by Django 5.2.8 on 2025-12-18 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0007_employeereimbursement'),
        ('organizations', '0011_trainingvideoview_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereimbursement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='organizations.organization'),
        ),
    ]
