# Generated by Django 6.0 on 2025-12-22 07:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0007_employeereimbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='House Rent Allowance')),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_esi', models.BooleanField(default=False, verbose_name='Has ESI')),
                ('esi_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='ESI Number')),
                ('esi_employee_share_percentage', models.DecimalField(decimal_places=2, default=0.75, help_text='Employee ESI contribution percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('esi_employer_share_percentage', models.DecimalField(decimal_places=2, default=3.25, help_text='Employer ESI contribution percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('has_pf', models.BooleanField(default=False, verbose_name='Has PF')),
                ('pf_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='PF Number')),
                ('uan_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='UAN Number')),
                ('pf_employee_share_percentage', models.DecimalField(decimal_places=2, default=12, help_text='Employee PF contribution percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pf_employer_share_percentage', models.DecimalField(decimal_places=2, default=13, help_text='Employer PF contribution percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pf_voluntary_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Voluntary PF contribution percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_voluntary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_info', to='apps_hr.employee')),
            ],
            options={
                'verbose_name_plural': 'Salaries',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_voluntary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='apps_hr.employee')),
            ],
            options={
                'verbose_name': 'Payroll Invoice',
                'verbose_name_plural': 'Payroll Invoices',
                'ordering': ['-year', '-month', 'employee__full_name'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
