# Generated by Django 6.0 on 2025-12-22 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0008_salary_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
