# Generated by Django 5.2.8 on 2025-12-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0009_employee_is_logged_in_attendance_latepunchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_hr.employee'),
        ),
    ]
