# Generated by Django 5.2.8 on 2025-12-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0010_alter_attendance_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latepunchrequest',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='latepunchrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='latepunchrequest',
            name='requested_at',
        ),
        migrations.AlterField(
            model_name='latepunchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
