# Generated by Django 5.2.8 on 2025-12-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0011_remove_latepunchrequest_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latepunchrequest',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_request', to='apps_hr.attendance'),
        ),
        migrations.AddField(
            model_name='latepunchrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latepunchrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='latepunchrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
