# Generated by Django 6.0 on 2025-12-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0009_alter_salary_effective_date'),
        ('apps_hr', '0013_latepunchrequest_approved_at_and_more'),
    ]

    operations = [
    ]
