# Generated by Django 5.2.8 on 2025-12-24 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0014_merge_20251223_1115'),
        ('organizations', '0014_alter_trainingcompletion_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='referrals/')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under Review'), ('interview', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('joined', 'Joined')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_hr.jobopening')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
