# Generated by Django 6.0 on 2025-12-26 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0018_jobopening_referral'),
        ('organizations', '0014_alter_trainingcompletion_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('organization', 'Organization'), ('project', 'Project')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_hr.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='hr/chat/files/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apps_hr.chatgroup')),
                ('private_recipients', models.ManyToManyField(blank=True, related_name='private_chat_messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UnreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_hr.chatgroup')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_hr.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['group', 'timestamp'], name='apps_hr_mes_group_i_61c2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='apps_hr_mes_timesta_2097b9_idx'),
        ),
        migrations.AddIndex(
            model_name='unreadmessage',
            index=models.Index(fields=['user', 'group'], name='apps_hr_unr_user_id_29baf9_idx'),
        ),
        migrations.AddIndex(
            model_name='unreadmessage',
            index=models.Index(fields=['group', 'user'], name='apps_hr_unr_group_i_16c1bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unreadmessage',
            unique_together={('user', 'message', 'group')},
        ),
    ]
