# Generated by Django 6.0 on 2025-12-26 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0019_chatgroup_message_unreadmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='manual_members',
            field=models.ManyToManyField(blank=True, help_text='Members manually added to this custom group', related_name='custom_chat_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('project', 'Project'), ('custom', 'Custom')], max_length=20),
        ),
    ]
