# Generated by Django 6.0 on 2025-12-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0020_chatgroup_created_by_chatgroup_manual_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Select employees who will work on and chat in this project', related_name='project_assignments', to='apps_hr.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='apps_hr.employee'),
        ),
    ]
