# Generated by Django 6.0 on 2025-12-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0021_project_members_alter_project_created_by'),
        ('organizations', '0014_alter_trainingcompletion_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Employees assigned to this project — they will see the project chat', related_name='project_assignments', to='apps_hr.employee'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_project_name_per_organization'),
        ),
    ]
