# Generated by Django 6.0 on 2025-12-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0015_jobopening_referral'),
        ('apps_hr', '0023_alter_employee_user'),
    ]

    operations = [
    ]
