# Generated by Django 6.0 on 2025-12-30 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0024_merge_20251230_1256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='manual_members',
            field=models.ManyToManyField(blank=True, related_name='custom_chat_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
