# Generated by Django 6.0 on 2026-01-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0017_chatgroup_message_unreadmessage_project_members_and_more'),
        ('apps_hr', '0025_alter_chatgroup_manual_members'),
    ]

    operations = [
    ]
