# Generated by Django 6.0 on 2026-01-06 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0026_merge_20260105_1244'),
        ('organizations', '0017_organizationbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTLReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data', models.JSONField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_received_reports', to='apps_hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_sent_reports', to='apps_hr.employee')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('team_lead', 'date')},
            },
        ),
    ]
