# Generated by Django 6.0 on 2026-01-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0026_merge_20260106_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinvite',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_reportees', to='apps_hr.employee'),
        ),
    ]
