# Generated by Django 6.0 on 2026-01-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0027_employeeinvite_reporting_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinvite',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
