# Generated by Django 6.0 on 2026-01-06 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0027_dailytlreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytlreport',
            options={'ordering': ['-date', '-sent_at'], 'verbose_name': 'Daily Team Lead Report', 'verbose_name_plural': 'Daily Team Lead Reports'},
        ),
        migrations.AddField(
            model_name='dailytlreport',
            name='is_submitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailytlreport',
            name='report_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dailytlreport',
            name='data',
            field=models.JSONField(blank=True, help_text='Optional structured data: tasks completed, attendance, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='dailytlreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailytlreport',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_received_tl_reports', to='apps_hr.employee'),
        ),
        migrations.AlterField(
            model_name='dailytlreport',
            name='team_lead',
            field=models.ForeignKey(limit_choices_to={'role': 'team_lead'}, on_delete=django.db.models.deletion.CASCADE, related_name='tl_sent_reports', to='apps_hr.employee'),
        ),
    ]
