# Generated by Django 6.0 on 2026-01-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_hr', '0028_alter_dailytlreport_options_and_more'),
        ('apps_hr', '0028_alter_employeeinvite_email'),
    ]

    operations = [
    ]
