# Generated by Django 6.0 on 2026-03-20 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('sales', '0006_alter_salesorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
    ]
