# Generated by Django 6.0 on 2026-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_grn_options_alter_grnitem_options_and_more'),
        ('production', '0002_alter_productionplan_sales_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to deactivate this BOM version'),
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterial',
            unique_together={('product', 'version')},
        ),
    ]
