# Generated by Django 6.0 on 2026-03-25 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_machine_code'),
        ('production', '0002_create_production_order_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['planned_start'], 'verbose_name': 'Production Order', 'verbose_name_plural': 'Production Orders'},
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='item',
            field=models.ForeignKey(help_text='The item/finished good to produced', on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='inventory.machine'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='production_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='production.productionplan'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='run_time_per_unit_hours',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Processing time per unit in hours', max_digits=8),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('done', 'Done')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='inventory.machine')),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='production.manufacturingorder')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
