# Generated by Django 6.0 on 2026-03-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_machine_code'),
        ('production', '0002_alter_productionplan_sales_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mooperation',
            name='work_center',
        ),
        migrations.RemoveField(
            model_name='routingoperation',
            name='work_center',
        ),
        migrations.AddField(
            model_name='mooperation',
            name='machine',
            field=models.ForeignKey(default=2, help_text='Machine assigned for this operation', on_delete=django.db.models.deletion.CASCADE, to='inventory.machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='machine',
            field=models.ForeignKey(default=2, help_text='Machine/work center used for this operation', on_delete=django.db.models.deletion.CASCADE, to='inventory.machine'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorkCenter',
        ),
    ]
