# Generated by Django 6.0 on 2026-03-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_mooperation_work_center_and_more'),
        ('sales', '0006_alter_salesorder_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionplan',
            name='sales_order',
        ),
        migrations.AddField(
            model_name='productionplan',
            name='sales_orders',
            field=models.ManyToManyField(blank=True, related_name='production_plans', to='sales.salesorder'),
        ),
    ]
