# Generated by Django 6.0 on 2026-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_productionplan_sales_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedorder',
            name='scheduling_type',
            field=models.CharField(choices=[('basic', 'Basic Scheduling'), ('lead_time', 'Lead Time Scheduling')], default='basic', max_length=20),
        ),
    ]
