# Generated by Django 6.0 on 2026-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_plannedorder_scheduling_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Planned Order', 'verbose_name_plural': 'Planned Orders'},
        ),
        migrations.AddField(
            model_name='plannedorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this planned order was created', null=True),
        ),
        migrations.AddField(
            model_name='plannedorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this planned order', null=True),
        ),
        migrations.AddField(
            model_name='plannedorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this planned order was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='scheduling_type',
            field=models.CharField(choices=[('production', 'Production Order'), ('purchase', 'Purchase Order'), ('basic', 'Basic Scheduling'), ('lead_time', 'Lead Time Scheduling')], default='production', max_length=20),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
