# Generated by Django 6.0 on 2026-03-23 06:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_machine_code'),
        ('organizations', '0020_alter_organizationuser_role'),
        ('production', '0007_update_planned_order_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routingoperation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='routingoperation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mooperation',
            name='planned_finish',
        ),
        migrations.RemoveField(
            model_name='mooperation',
            name='planned_start',
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine assigned for this operation', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.machine'),
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mooperation',
            name='sequence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine/work center used for this operation', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.machine'),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='sequence',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity_per_day_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('number_of_machines', models.PositiveSmallIntegerField(default=1)),
                ('efficiency_percentage', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Work Center',
                'verbose_name_plural': 'Work Centers',
            },
        ),
        migrations.RemoveField(
            model_name='routingoperation',
            name='labor_time_per_unit',
        ),
        migrations.RemoveField(
            model_name='routingoperation',
            name='machine_time_per_unit',
        ),
        migrations.RemoveField(
            model_name='routingoperation',
            name='setup_time_hours',
        ),
    ]
