# Generated by Django 6.0 on 2026-03-23 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_item_type_alter_machine_code_itemdependency'),
        ('production', '0008_alter_routingoperation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='machine',
            field=models.ForeignKey(help_text='Machine assigned for this operation', on_delete=django.db.models.deletion.CASCADE, to='inventory.machine'),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='expected_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='machine',
            field=models.ForeignKey(help_text='Machine/work center used for this operation', on_delete=django.db.models.deletion.CASCADE, to='inventory.machine'),
        ),
    ]
