# Generated by Django 6.0 on 2026-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_billofmaterial_machine_and_more'),
        ('sales', '0006_alter_salesorder_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='plannedorder',
            name='sales_orders',
            field=models.ManyToManyField(blank=True, related_name='planned_orders', to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
