# Generated by Django 6.0 on 2026-03-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_machine_code'),
        ('production', '0010_alter_plannedorder_options_plannedorder_sales_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine assigned for this operation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.machine'),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
