// src/pages/inventory/MachineEdit.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Factory, Save, ArrowLeft, AlertCircle, RefreshCw, Clock, DollarSign, Settings, Wrench } from 'lucide-react';
import api from '../../../services/api';

export default function MachineEdit() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    // Core Identification
    name: '',
    code: '', // Read-only - auto-generated by backend
    department: null,
    
    // Type & Status
    work_center_type: 'machine',
    maintenance_status: 'operational',
    is_active: true,
    
    // Capacity Planning
    capacity_per_day_hours: 8,
    efficiency_percentage: 100.00,
    utilization_percentage: 100.00,
    
    // Lead Time Fields
    default_queue_time_hours: 0,
    setup_time_hours: 0,
    
    // Costing Fields
    hourly_labor_cost: 0,
    hourly_overhead_cost: 0,
    
    // Maintenance
    last_maintenance_date: '',
    next_maintenance_date: '',
    
    // Additional
    description: '',
  });

  const [departments, setDepartments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [fieldErrors, setFieldErrors] = useState({});
  const [activeTab, setActiveTab] = useState('basic');

  // Work center type options from model
  const workCenterTypes = [
    { value: 'machine', label: 'Machine Tool' },
    { value: 'assembly', label: 'Assembly Station' },
    { value: 'inspection', label: 'Quality Station' },
    { value: 'labor', label: 'Manual Work' },
  ];

  // Maintenance status options from model
  const maintenanceStatuses = [
    { value: 'operational', label: 'Operational' },
    { value: 'maintenance', label: 'Under Maintenance' },
    { value: 'breakdown', label: 'Breakdown' },
  ];

  const tabs = [
    { id: 'basic', label: 'Basic Info', icon: Factory },
    { id: 'capacity', label: 'Capacity', icon: Clock },
    { id: 'leadtime', label: 'Lead Time', icon: Settings },
    { id: 'costing', label: 'Costing', icon: DollarSign },
    { id: 'maintenance', label: 'Maintenance', icon: Wrench },
  ];

  // Fetch both departments and current machine data
  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      setError(null);
      
      try {
        // Load departments
        const deptRes = await api.get('/hr/departments/');
        setDepartments(deptRes.data || []);

        // Load existing machine
        const machineRes = await api.get(`/inventory/machines/${id}/`);
        const machine = machineRes.data;

        setFormData({
          // Core Identification
          name: machine.name || '',
          code: machine.code || '',
          department: machine.department || null,
          
          // Type & Status
          work_center_type: machine.work_center_type || 'machine',
          maintenance_status: machine.maintenance_status || 'operational',
          is_active: machine.is_active !== false,
          
          // Capacity Planning
          capacity_per_day_hours: machine.capacity_per_day_hours || 8,
          efficiency_percentage: machine.efficiency_percentage || 100.00,
          utilization_percentage: machine.utilization_percentage || 100.00,
          
          // Lead Time Fields
          default_queue_time_hours: machine.default_queue_time_hours || 0,
          setup_time_hours: machine.setup_time_hours || 0,
          
          // Costing Fields
          hourly_labor_cost: machine.hourly_labor_cost || 0,
          hourly_overhead_cost: machine.hourly_overhead_cost || 0,
          
          // Maintenance
          last_maintenance_date: machine.last_maintenance_date || '',
          next_maintenance_date: machine.next_maintenance_date || '',
          
          // Additional
          description: machine.description || '',
        });
      } catch (err) {
        console.error('Error fetching data:', err);
        setError(
          err.response?.data?.detail ||
          'Failed to load machine or departments. Please try again.'
        );
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchData();
    }
  }, [id]);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    
    // Clear field error when user starts typing
    if (fieldErrors[name]) {
      setFieldErrors(prev => ({ ...prev, [name]: null }));
    }
    
    setFormData((prev) => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : 
              type === 'number' ? (value === '' ? '' : Number(value)) : 
              value,
    }));
  };

  const handleDateChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value || null,
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);
    setFieldErrors({});
    setSubmitting(true);

    // Prepare data for submission - exclude code as it's read-only
    const { code, ...submitFormData } = formData;
    
    const submitData = {
      ...submitFormData,
      department: formData.department ? parseInt(formData.department) : null,
      last_maintenance_date: formData.last_maintenance_date || null,
      next_maintenance_date: formData.next_maintenance_date || null,
    };

    // Remove empty description if not needed
    if (!submitData.description) {
      delete submitData.description;
    }

    console.log('Updating machine data:', submitData);

    try {
      await api.put(`/inventory/machines/${id}/`, submitData);
      
      // Show success message
      alert('Machine updated successfully');
      
      // Navigate back to machine list
      navigate('/machines-list', { 
        state: { message: 'Machine updated successfully!' } 
      });
    } catch (err) {
      console.error('Update error:', err);
      console.error('Error response:', err.response);
      console.error('Error data:', err.response?.data);
      
      // Handle field-level errors
      if (err.response?.data) {
        const responseData = err.response.data;
        
        if (typeof responseData === 'object') {
          if (responseData.detail) {
            setError(responseData.detail);
          } else if (responseData.non_field_errors) {
            setError(responseData.non_field_errors[0]);
          } else {
            // Check for field-level errors
            const fieldErrors = {};
            let hasFieldErrors = false;
            
            Object.keys(responseData).forEach(key => {
              if (Array.isArray(responseData[key])) {
                fieldErrors[key] = responseData[key][0];
                hasFieldErrors = true;
              } else if (typeof responseData[key] === 'string') {
                fieldErrors[key] = responseData[key];
                hasFieldErrors = true;
              }
            });
            
            if (hasFieldErrors) {
              setFieldErrors(fieldErrors);
            } else {
              setError('Failed to update machine. Please check all fields.');
            }
          }
        } else if (typeof responseData === 'string') {
          setError(responseData);
        } else {
          setError('Failed to update machine. Please check all fields.');
        }
      } else {
        setError('Network error. Please check your connection.');
      }
    } finally {
      setSubmitting(false);
    }
  };

  // Removed loading message - now showing the form immediately
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 to-gray-900 text-gray-100 flex flex-col">
      {/* Header */}
      <header className="bg-gray-900/90 border-b border-cyan-900/50 px-6 py-4 flex justify-between items-center backdrop-blur-sm">
        <div className="flex items-center gap-4">
          <Factory className="w-9 h-9 text-cyan-400" />
          <div>
            <h1 className="text-2xl font-bold text-cyan-300">Edit Machine</h1>
            <p className="text-sm text-gray-400">
              {new Date().toLocaleDateString('en-IN')} • ID: {id}
            </p>
          </div>
        </div>

        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 px-4 py-2 bg-gray-800 hover:bg-gray-700 rounded-lg text-sm border border-gray-700"
        >
          <ArrowLeft size={16} />
          Back
        </button>
      </header>

      {/* Main Content */}
      <div className="flex-1 p-6 md:p-8 overflow-auto">
        <div className="max-w-4xl mx-auto">
          <div className="bg-gray-900/70 rounded-2xl border border-cyan-900/40 backdrop-blur-sm shadow-xl p-8">
            {error && (
              <div className="bg-red-900/60 border border-red-700 text-red-200 p-4 rounded-xl mb-6 flex items-start gap-3">
                <AlertCircle size={20} className="mt-1 flex-shrink-0" />
                <span>{error}</span>
              </div>
            )}

            {/* Tabs */}
            <div className="flex flex-wrap gap-2 mb-8 border-b border-gray-800 pb-4">
              {tabs.map((tab) => {
                const Icon = tab.icon;
                return (
                  <button
                    key={tab.id}
                    type="button"
                    onClick={() => setActiveTab(tab.id)}
                    className={`flex items-center gap-2 px-4 py-2 rounded-lg transition-all ${
                      activeTab === tab.id
                        ? 'bg-cyan-600 text-white'
                        : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
                    }`}
                  >
                    <Icon size={16} />
                    {tab.label}
                  </button>
                );
              })}
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Basic Info Tab */}
              {activeTab === 'basic' && (
                <div className="space-y-6">
                  <h3 className="text-lg font-semibold text-cyan-300 mb-4">Basic Information</h3>
                  
                  {/* Machine Name */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Machine Name <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="text"
                      name="name"
                      value={formData.name}
                      onChange={handleChange}
                      required
                      className={`w-full bg-gray-800 border ${
                        fieldErrors.name ? 'border-red-500' : 'border-gray-700'
                      } rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition`}
                      placeholder="CNC Lathe M1"
                    />
                    {fieldErrors.name && (
                      <p className="mt-1 text-sm text-red-400">{fieldErrors.name}</p>
                    )}
                  </div>

                  {/* Code - Read-only field */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">Machine Code</label>
                    <input
                      type="text"
                      name="code"
                      value={formData.code}
                      readOnly
                      disabled
                      className="w-full bg-gray-800/50 border border-gray-700 rounded-lg px-4 py-3 text-gray-400 cursor-not-allowed"
                    />
                    <p className="mt-1 text-xs text-gray-500">Machine code is auto-generated and cannot be changed</p>
                  </div>

                  {/* Department */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">Department</label>
                    <select
                      name="department"
                      value={formData.department || ''}
                      onChange={handleChange}
                      className={`w-full bg-gray-800 border ${
                        fieldErrors.department ? 'border-red-500' : 'border-gray-700'
                      } rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition`}
                    >
                      <option value="">— Select Department —</option>
                      {departments.map((dept) => (
                        <option key={dept.id} value={dept.id}>
                          {dept.name} {dept.code && `(${dept.code})`}
                        </option>
                      ))}
                    </select>
                    {fieldErrors.department && (
                      <p className="mt-1 text-sm text-red-400">{fieldErrors.department}</p>
                    )}
                  </div>

                  {/* Work Center Type */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Work Center Type <span className="text-red-400">*</span>
                    </label>
                    <select
                      name="work_center_type"
                      value={formData.work_center_type}
                      onChange={handleChange}
                      required
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    >
                      {workCenterTypes.map((type) => (
                        <option key={type.value} value={type.value}>
                          {type.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Maintenance Status */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Maintenance Status
                    </label>
                    <select
                      name="maintenance_status"
                      value={formData.maintenance_status}
                      onChange={handleChange}
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    >
                      {maintenanceStatuses.map((status) => (
                        <option key={status.value} value={status.value}>
                          {status.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  {/* Active Checkbox */}
                  <div className="flex items-center space-x-3">
                    <input
                      type="checkbox"
                      name="is_active"
                      checked={formData.is_active}
                      onChange={handleChange}
                      className="h-5 w-5 text-cyan-600 focus:ring-cyan-500 border-gray-600 rounded bg-gray-800"
                    />
                    <label className="text-gray-300 font-medium">Active / Available for production</label>
                  </div>

                  {/* Description */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">Description</label>
                    <textarea
                      name="description"
                      value={formData.description}
                      onChange={handleChange}
                      rows={3}
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                      placeholder="Brief description or notes about this machine..."
                    />
                  </div>
                </div>
              )}

              {/* Capacity Tab */}
              {activeTab === 'capacity' && (
                <div className="space-y-6">
                  <h3 className="text-lg font-semibold text-cyan-300 mb-4">Capacity Planning</h3>
                  
                  {/* Capacity per day */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Capacity per day (hours) <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="number"
                      name="capacity_per_day_hours"
                      value={formData.capacity_per_day_hours}
                      onChange={handleChange}
                      min="1"
                      max="24"
                      step="1"
                      required
                      className={`w-full bg-gray-800 border ${
                        fieldErrors.capacity_per_day_hours ? 'border-red-500' : 'border-gray-700'
                      } rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition`}
                    />
                    <p className="mt-1 text-xs text-gray-500">Hours available per day (e.g., 8 for single shift, 16 for double)</p>
                    {fieldErrors.capacity_per_day_hours && (
                      <p className="mt-1 text-sm text-red-400">{fieldErrors.capacity_per_day_hours}</p>
                    )}
                  </div>

                  {/* Efficiency Percentage */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Efficiency Percentage (%)
                    </label>
                    <input
                      type="number"
                      name="efficiency_percentage"
                      value={formData.efficiency_percentage}
                      onChange={handleChange}
                      min="0"
                      max="200"
                      step="0.01"
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    />
                    <p className="mt-1 text-xs text-gray-500">Efficiency % (new machine=95%, old=70%)</p>
                  </div>

                  {/* Utilization Percentage */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Utilization Percentage (%)
                    </label>
                    <input
                      type="number"
                      name="utilization_percentage"
                      value={formData.utilization_percentage}
                      onChange={handleChange}
                      min="0"
                      max="100"
                      step="0.01"
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    />
                    <p className="mt-1 text-xs text-gray-500">Utilization % (85% = 15% planned downtime)</p>
                  </div>
                </div>
              )}

              {/* Lead Time Tab */}
              {activeTab === 'leadtime' && (
                <div className="space-y-6">
                  <h3 className="text-lg font-semibold text-cyan-300 mb-4">Lead Time Settings</h3>
                  
                  {/* Default Queue Time */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Default Queue Time (hours)
                    </label>
                    <input
                      type="number"
                      name="default_queue_time_hours"
                      value={formData.default_queue_time_hours}
                      onChange={handleChange}
                      min="0"
                      step="0.5"
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    />
                    <p className="mt-1 text-xs text-gray-500">Hours job waits before processing</p>
                  </div>

                  {/* Setup Time */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Setup Time (hours)
                    </label>
                    <input
                      type="number"
                      name="setup_time_hours"
                      value={formData.setup_time_hours}
                      onChange={handleChange}
                      min="0"
                      step="0.5"
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    />
                    <p className="mt-1 text-xs text-gray-500">Standard setup/changeover time in hours</p>
                  </div>
                </div>
              )}

              {/* Costing Tab */}
              {activeTab === 'costing' && (
                <div className="space-y-6">
                  <h3 className="text-lg font-semibold text-cyan-300 mb-4">Costing Information</h3>
                  
                  {/* Hourly Labor Cost */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Hourly Labor Cost (₹)
                    </label>
                    <input
                      type="number"
                      name="hourly_labor_cost"
                      value={formData.hourly_labor_cost}
                      onChange={handleChange}
                      min="0"
                      step="0.01"
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    />
                    <p className="mt-1 text-xs text-gray-500">Cost per hour for operator</p>
                  </div>

                  {/* Hourly Overhead Cost */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Hourly Overhead Cost (₹)
                    </label>
                    <input
                      type="number"
                      name="hourly_overhead_cost"
                      value={formData.hourly_overhead_cost}
                      onChange={handleChange}
                      min="0"
                      step="0.01"
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    />
                    <p className="mt-1 text-xs text-gray-500">Cost per hour for electricity, maintenance</p>
                  </div>
                </div>
              )}

              {/* Maintenance Tab */}
              {activeTab === 'maintenance' && (
                <div className="space-y-6">
                  <h3 className="text-lg font-semibold text-cyan-300 mb-4">Maintenance Schedule</h3>
                  
                  {/* Last Maintenance Date */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Last Maintenance Date
                    </label>
                    <input
                      type="date"
                      name="last_maintenance_date"
                      value={formData.last_maintenance_date}
                      onChange={handleDateChange}
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    />
                  </div>

                  {/* Next Maintenance Date */}
                  <div>
                    <label className="block text-sm text-gray-300 mb-2 font-medium">
                      Next Maintenance Date
                    </label>
                    <input
                      type="date"
                      name="next_maintenance_date"
                      value={formData.next_maintenance_date}
                      onChange={handleDateChange}
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-cyan-500 focus:ring-1 focus:ring-cyan-500 transition"
                    />
                  </div>
                </div>
              )}

              {/* Navigation Buttons */}
              <div className="flex justify-between pt-6 border-t border-gray-800">
                <button
                  type="button"
                  onClick={() => {
                    const currentIndex = tabs.findIndex(t => t.id === activeTab);
                    if (currentIndex > 0) {
                      setActiveTab(tabs[currentIndex - 1].id);
                    }
                  }}
                  disabled={activeTab === tabs[0].id}
                  className={`px-6 py-2 rounded-lg ${
                    activeTab === tabs[0].id
                      ? 'bg-gray-800 text-gray-600 cursor-not-allowed'
                      : 'bg-gray-800 hover:bg-gray-700 text-white'
                  }`}
                >
                  Previous
                </button>
                
                <button
                  type="button"
                  onClick={() => {
                    const currentIndex = tabs.findIndex(t => t.id === activeTab);
                    if (currentIndex < tabs.length - 1) {
                      setActiveTab(tabs[currentIndex + 1].id);
                    }
                  }}
                  disabled={activeTab === tabs[tabs.length - 1].id}
                  className={`px-6 py-2 rounded-lg ${
                    activeTab === tabs[tabs.length - 1].id
                      ? 'bg-gray-800 text-gray-600 cursor-not-allowed'
                      : 'bg-gray-800 hover:bg-gray-700 text-white'
                  }`}
                >
                  Next
                </button>
              </div>

              {/* Submit Button */}
              <div className="flex flex-col sm:flex-row gap-4 pt-6">
                <button
                  type="submit"
                  disabled={submitting}
                  className={`flex-1 py-3 px-6 rounded-xl font-medium transition-all flex items-center justify-center gap-2 ${
                    submitting
                      ? 'bg-gray-700 cursor-not-allowed text-gray-400'
                      : 'bg-gradient-to-r from-cyan-600 to-cyan-700 hover:from-cyan-500 hover:to-cyan-600 shadow-lg shadow-cyan-900/30'
                  }`}
                >
                  {submitting ? (
                    <>
                      <RefreshCw className="animate-spin" size={18} />
                      Saving Changes...
                    </>
                  ) : (
                    <>
                      <Save size={18} />
                      Save Changes
                    </>
                  )}
                </button>

                <button
                  type="button"
                  onClick={() => navigate(-1)}
                  className="flex-1 py-3 px-6 bg-gray-800 hover:bg-gray-700 border border-gray-600 rounded-xl font-medium transition"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}