# Generated by Django 5.1 on 2025-12-26 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('pan_number', models.CharField(blank=True, default='', max_length=10)),
                ('cin_number', models.CharField(blank=True, default='', max_length=21)),
                ('base_currency', models.CharField(default='INR', max_length=3)),
                ('time_zone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('accounting_standards', models.CharField(default='Indian GAAP', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bank name + branch or account nickname', max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC Code (11 characters)', max_length=11)),
                ('micr_code', models.CharField(blank=True, help_text='MICR Code (9 digits)', max_length=9, null=True)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('cc', 'Cash Credit'), ('od', 'Overdraft'), ('fixed_deposit', 'Fixed Deposit'), ('other', 'Other')], default='savings', max_length=20)),
                ('pan_number', models.CharField(blank=True, help_text='PAN linked to account (optional)', max_length=10)),
                ('cin_number', models.CharField(blank=True, help_text='For company accounts', max_length=21)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='finance.company')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], max_length=10)),
                ('code', models.CharField(help_text='e.g., 1001, 2100-01', max_length=20, unique=True)),
                ('is_group', models.BooleanField(default=False, help_text='True for Group (e.g., Current Assets), False for Ledger')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_related', models.BooleanField(default=False, help_text='Mark for GST/TDS accounts')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.company')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='finance.company')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='finance.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to='finance.company')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('company', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mismatch_note', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. GST 18%, GST 12%, IGST 5%', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_type', models.CharField(choices=[('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST'), ('UTGST', 'UTGST'), ('VAT', 'VAT'), ('CESS', 'CESS'), ('OTHER', 'Other')], default='IGST', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this tax rate currently applicable?')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date from which this rate applies')),
                ('hsn_sac_required', models.BooleanField(default=True, help_text='Requires HSN/SAC code on invoices?')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='finance.company')),
                ('financial_year', models.ForeignKey(blank=True, help_text='Tax rate applicable for this financial year', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_rates', to='finance.financialyear')),
            ],
            options={
                'ordering': ['-rate', 'name'],
                'unique_together': {('company', 'financial_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SALE', 'Sales Invoice'), ('PURCHASE', 'Purchase Bill'), ('EXPENSE', 'Expense Entry'), ('PAYROLL', 'Payroll'), ('JOURNAL', 'Manual Journal'), ('PAYMENT', 'Payment Made'), ('RECEIPT', 'Payment Received')], max_length=10)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Invoice/Bill No.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.company')),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='finance.account')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='finance.customer')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='finance.account')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialyear')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Item/Service name', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.taxrate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='finance.company')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='finance.vendor'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.company')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_payments', to='finance.bankaccount')),
                ('to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.customer')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction')),
                ('to_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialyear')),
            ],
            options={
                'unique_together': {('account', 'financial_year')},
            },
        ),
    ]
