# Generated by Django 6.0 on 2026-01-12 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_voucher_unique_together_and_more'),
        ('organizations', '0018_alter_organizationuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybudget',
            options={},
        ),
        migrations.RemoveField(
            model_name='monthlybudget',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monthlybudget',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
