# Generated by Django 6.0 on 2026-01-12 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('finance', '0001_initial'),
    ('organizations', '0019_alter_organizationuser_role'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]


    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('vendor_code', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, help_text='Full address in one field')),
                ('gst_number', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('msme_number', models.CharField(blank=True, max_length=30, verbose_name='MSME / UDYAM')),
                ('vendor_type', models.CharField(choices=[('local', 'Local'), ('outstation', 'Outstation'), ('import', 'Import/Overseas'), ('service', 'Service Provider'), ('goods', 'Goods Supplier')], default='goods', max_length=50)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'name'], name='finance_ven_organiz_d9d9c6_idx'), models.Index(fields=['organization', 'gst_number'], name='finance_ven_organiz_bb5342_idx')],
                'unique_together': {('organization', 'vendor_code')},
            },
        ),
    ]
