# Generated by Django 5.2.8 on 2025-11-27 05:28

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='default_modules',
        ),
        migrations.AddField(
            model_name='module',
            name='app_name',
            field=models.CharField(default='apps.core', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='base_url',
            field=models.CharField(default='/modules', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='module_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationmodule',
            name='accessible_pages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='organizationmodule',
            name='org_module_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(choices=[('hr_management', 'HR Management'), ('inventory', 'Inventory Management'), ('sales', 'Sales Management'), ('transport', 'Transport Management'), ('accounting', 'Accounting'), ('crm', 'CRM'), ('project_management', 'Project Management')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_assignments', to='subscriptions.module'),
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_modules', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 11, 27, 5, 26, 27, 398795, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('trial', 'Trial'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
        migrations.CreateModel(
            name='PlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.module')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'plan_modules',
                'unique_together': {('plan', 'module')},
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='included_modules',
            field=models.ManyToManyField(related_name='plans', through='subscriptions.PlanModule', to='subscriptions.module'),
        ),
        migrations.CreateModel(
            name='ModulePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('required_permission', models.CharField(default='view', max_length=50)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='subscriptions.module')),
            ],
            options={
                'db_table': 'module_pages',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'code')},
            },
        ),
    ]
