# Generated by Django 5.2.8 on 2025-11-27 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_module_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 11, 27, 5, 28, 9, 560861, tzinfo=datetime.timezone.utc)),
        ),
    ]
