# Generated by Django 5.2.8 on 2025-11-27 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 11, 27, 6, 2, 36, 57052, tzinfo=datetime.timezone.utc)),
        ),
    ]
