# Generated by Django 5.2.7 on 2025-11-27 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 11, 27, 6, 20, 10, 638904, tzinfo=datetime.timezone.utc)),
        ),
    ]
