# Generated by Django 5.2.7 on 2025-11-27 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_options_and_more'),
        ('subscriptions', '0005_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modulepage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planmodule',
            options={'verbose_name': 'Plan Module', 'verbose_name_plural': 'Plan Modules'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='monthly_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='module',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='module',
            name='version',
        ),
        migrations.RemoveField(
            model_name='organizationmodule',
            name='org_module_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='included_modules',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_sub_organizations',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='yearly_price',
        ),
        migrations.AddField(
            model_name='planmodule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='app_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='base_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='modulepage',
            name='required_permission',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.module'),
        ),
        migrations.AlterField(
            model_name='organizationmodule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_modules', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='planmodule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='module',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modulepage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organizationmodule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='planmodule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subscription',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table=None,
        ),
    ]
