# Generated by Django 6.0 on 2026-01-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_module_options_alter_modulepage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepage',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
