# Generated by Django 6.0 on 2026-01-05 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_created_at_and_more'),
        ('organizations', '0017_organizationbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('main_org_admin', 'Main Organization Admin'), ('sub_org_admin', 'Sub Organization Admin'), ('hr_manager', 'HR Manager'), ('Manager', 'Manager'), ('TL', 'Team Lead'), ('team_lead', 'Team Lead'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
