# Generated by Django 6.0 on 2026-01-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_organization_alter_user_role'),
        ('organizations', '0017_organizationbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('main_org_admin', 'Main Organization Admin'), ('sub_org_admin', 'Sub Organization Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
