# Generated by Django 6.0 on 2026-01-10 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_organization_alter_user_role'),
        ('organizations', '0017_organizationbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('SALES', 'Sales Invoice'), ('PURCHASE', 'Purchase Invoice'), ('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('JOURNAL', 'Journal')], max_length=20)),
                ('voucher_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='organizations.organization')),
            ],
            options={
                'db_table': 'accounts_voucher',
                'unique_together': {('organization', 'voucher_number')},
            },
        ),
    ]
