# Generated by Django 6.0 on 2026-01-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_voucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
