# Generated by Django 6.0 on 2026-01-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('accounts', '0006_delete_voucher'),
    ]

    operations = [
    ]
