# Generated by Django 6.0 on 2026-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Optional – last 4 digits only for privacy', max_length=12, verbose_name='Aadhaar Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternate / WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_type',
            field=models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership Firm'), ('private_limited', 'Private Limited Company'), ('limited_liability_partnership', 'LLP'), ('public_limited', 'Public Limited Company'), ('huf', 'HUF'), ('trust', 'Trust / Society'), ('other', 'Other')], default='', max_length=50, verbose_name='Business Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit (₹)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, help_text='15-digit GST Identification Number', max_length=15, verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='Industry / Sector'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number (10 characters)', max_length=10, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Payment Terms (days)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Shipping Address'),
        ),
    ]
