# Generated by Django 6.0 on 2026-02-27 05:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('organizations', '0019_alter_organizationuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_ended', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('no_answer', 'No Answer'), ('busy', 'Busy'), ('left_voicemail', 'Left Voicemail'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('appointment_set', 'Appointment Set'), ('follow_up_later', 'Follow Up Later'), ('wrong_number', 'Wrong Number'), ('other', 'Other')], default='other', max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-call_started'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at', 'next_followup_date']},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='crm_contact_email_240305_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='crm_opportu_contact_93b6a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='crm_opportu_stage_ea8c40_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='followup_priority',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('follow_up', 'Follow-up Needed'), ('won', 'Won / Customer'), ('lost', 'Lost'), ('inactive', 'Inactive')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=50),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['next_followup_date', 'followup_priority'], name='crm_contact_next_fo_2c7e4d_idx'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='called_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calllog',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='crm.contact'),
        ),
    ]
