# Generated by Django 6.0 on 2026-02-27 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_calllog_alter_contact_options_and_more'),
        ('organizations', '0019_alter_organizationuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='called_by',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Opportunity', 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='crm_contact_next_fo_2c7e4d_idx',
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('customer', 'Customer'), ('inactive', 'Inactive'), ('supplier', 'Supplier'), ('partner', 'Partner')], default='lead', max_length=30),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.PositiveSmallIntegerField(default=10, help_text='Estimated success probability %'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=50),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_240305_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['contact', 'stage'], name='crm_opportu_contact_93b6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage', 'expected_close_date'], name='crm_opportu_stage_ea8c40_idx'),
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='followup_priority',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_contacted_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='next_followup_date',
        ),
    ]
