# Generated by Django 6.0 on 2026-03-03 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_contact_status_alter_opportunity_stage_and_more'),
        ('organizations', '0019_alter_organizationuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('needs_analysis', 'Needs Analysis'), ('value_proposition', 'Value Proposition'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospecting', max_length=50)),
                ('probability', models.PositiveSmallIntegerField(default=10)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('junk', 'Junk'), ('converted', 'Converted')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='called_by',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='crm_opportu_contact_93b6a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='crm_opportu_stage_ea8c40_idx',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='sales_order',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='crm_contact_organiz_44c566_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='crm_contact_email_240305_idx',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organizations.organization'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
        migrations.DeleteModel(
            name='SalesOrderItem',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='next_follow_up',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='position',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
