# Generated by Django 6.0 on 2026-05-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
