# Generated by Django 6.0 on 2026-05-29 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_rename_phone_driver_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
