# Generated by Django 6.0 on 2026-06-01 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_machine_code'),
        ('sales', '0011_salesinvoiceitem_returned_qty'),
        ('transport', '0003_alter_driver_joining_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporttrip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transport Trip', 'verbose_name_plural': 'Transport Trips'},
        ),
        migrations.AlterModelOptions(
            name='transporttripitem',
            options={'ordering': ['trip', 'id']},
        ),
        migrations.RenameField(
            model_name='transporttrip',
            old_name='loading_time',
            new_name='loading_end_time',
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='fuel_efficiency',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='loading_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='trip_type',
            field=models.CharField(choices=[('outbound', 'Outbound Delivery'), ('inbound', 'Inbound / Return'), ('transfer', 'Internal Transfer'), ('other', 'Other')], default='outbound', max_length=20),
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='unloading_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='unloading_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporttripitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transporttripitem',
            name='ordered_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transporttripitem',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_items', to='sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='transporttripitem',
            name='short_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transporttripitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AlterUniqueTogether(
            name='transporttripitem',
            unique_together={('trip', 'sales_order_item')},
        ),
    ]
