# Generated by Django 6.0 on 2026-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_transporttrip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportroute',
            name='route_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
