# Generated by Django 6.0 on 2026-06-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_transportroute_route_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportroute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transport Route'},
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='route_code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
