# Generated by Django 6.0 on 2026-06-03 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organizationuser_role'),
        ('transport', '0006_alter_transportroute_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemaintenance',
            options={'ordering': ['-service_date']},
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenance',
            index=models.Index(fields=['vehicle', 'status'], name='transport_v_vehicle_7f9b62_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemaintenance',
            index=models.Index(fields=['next_service_date'], name='transport_v_next_se_98c423_idx'),
        ),
    ]
