# Generated by Django 6.0 on 2026-06-04 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organizationuser_role'),
        ('transport', '0007_alter_vehiclemaintenance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportexpense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'Transport Expense', 'verbose_name_plural': 'Transport Expenses'},
        ),
        migrations.AddField(
            model_name='transportexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transportexpense',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='transportexpense',
            index=models.Index(fields=['organization', 'expense_date'], name='transport_t_organiz_3d2ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='transportexpense',
            index=models.Index(fields=['trip', 'expense_type'], name='transport_t_trip_id_3b7ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='transportexpense',
            index=models.Index(fields=['created_at'], name='transport_t_created_93d6d1_idx'),
        ),
    ]
