# Generated by Django 6.0 on 2026-06-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_alter_transportexpense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportinvoice',
            options={'ordering': ['-invoice_date', '-created_at'], 'verbose_name': 'Transport Invoice', 'verbose_name_plural': 'Transport Invoices'},
        ),
        migrations.AddField(
            model_name='transportinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transportinvoice',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='transport.transporttrip'),
        ),
    ]
