from django.urls import path
from .views import (
    ConvertToCustomerView,
    CreateQuotationFromLeadView,
    CustomerDetailView,
    CustomerListView,
    CustomerUpdateView,
    FollowUpListCreateView,
    GSTSettingsAPIView,
    QualifiedLeadsListView,
    QualifiedLeadDetailView,
    QuotationListView,
    QuotationDetailView,
    QuotationStatusUpdateView,
    SalesOrderCreateView,
    SalesOrderDeleteView,
    SalesOrderListView,
    SalesOrderStatusUpdateView,
    SalesOrderUpdateView,
)

urlpatterns = [
    path('qualified-leads/', QualifiedLeadsListView.as_view()),
path('qualified-leads/<int:id>/', QualifiedLeadDetailView.as_view()),
path('quotations/create-from-lead/', CreateQuotationFromLeadView.as_view()),
path('quotations/', QuotationListView.as_view()),
path('quotations/<int:pk>/', QuotationDetailView.as_view()),
path('quotations/<int:pk>/status/', QuotationStatusUpdateView.as_view()),
path('quotations/<int:quotation_id>/followups/', FollowUpListCreateView.as_view()),
path('quotations/<int:pk>/convert-to-customer/', ConvertToCustomerView.as_view(), name='convert-to-customer'),
path('customers/', CustomerListView.as_view(), name='customer-list'),
path('customers/<int:pk>/', CustomerDetailView.as_view(), name='customer-detail'),
path('customers/<int:pk>/edit/', CustomerUpdateView.as_view(), name='customer-update'),
path('sales-orders/create/', SalesOrderCreateView.as_view(), name='sales-order-create'),
path('sales-orders/', SalesOrderListView.as_view(), name='sales-order-list'),
path('sales-orders/<int:pk>/', SalesOrderDeleteView.as_view(), name='sales-order-delete'),
path('gst-settings/', GSTSettingsAPIView.as_view(), name='gst-settings'),

path('sales-orders/<int:pk>/status/', SalesOrderStatusUpdateView.as_view(), name='sales-order-status'),
]