# Generated by Django 6.0 on 2026-03-09 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('sales', '0002_alter_quotation_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='call', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(help_text='When this follow-up is planned')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this follow-up was actually completed', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this quotation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_approved_quotations', related_query_name='sales_quotation_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount including tax', max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated GST/Tax amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes or special remarks'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('in_negotiation', 'In Negotiation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms',
            field=models.TextField(blank=True, default='1. Prices are valid for 30 days unless otherwise stated.\n2. Payment terms: 50% advance, balance on delivery.\n3. Subject to our standard terms and conditions.', help_text='Terms and conditions printed on quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity_date',
            field=models.DateField(blank=True, help_text='Date until which this quotation is valid', null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Sales person who created this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_created_quotations', related_query_name='sales_quotation_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='lead',
            field=models.ForeignKey(help_text='The qualified lead this quotation was created from', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF version of the quotation', null=True, upload_to='quotations/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(help_text='Unique quotation number (e.g. QTN-202503-0001)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', 'created_at'], name='sales_quota_status_55b6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quote_number'], name='sales_quota_quote_n_77bfb5_idx'),
        ),
        migrations.AddField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_followups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='sales.quotation'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status', 'scheduled_at'], name='sales_follo_status_a1e03d_idx'),
        ),
    ]
