# Generated by Django 6.0 on 2026-03-10 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_grn_options_alter_grnitem_options_and_more'),
        ('sales', '0004_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
    ]
