# Generated by Django 6.0 on 2026-04-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesinvoice_salesinvoiceitem_salespayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
