# Generated by Django 6.0 on 2026-04-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='returned_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
