# Generated by Django 5.2.8 on 2025-11-27 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('main', 'Main Organization'), ('sub', 'Sub Organization')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_organizations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan_tier',
            field=models.CharField(default='enterprise', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
    ]
