# Generated by Django 5.2.8 on 2025-12-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_code_organizationuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('accessible_pages', models.JSONField(default=list)),
                ('organization_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='organizations.organizationuser')),
            ],
            options={
                'unique_together': {('organization_user', 'module_code')},
            },
        ),
    ]
