# Generated by Django 5.2.8 on 2025-12-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationusermoduleaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationUserModuleAccess',
        ),
    ]
