# Generated by Django 5.2.8 on 2025-12-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_trainingcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideoview',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingvideoview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
