# Generated by Django 5.2.8 on 2025-12-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_trainingvideoview_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingvideoview',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization this view record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_video_views', to='organizations.organization'),
        ),
    ]
