# Generated by Django 5.2.8 on 2025-12-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_trainingvideoview_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcompletion',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
