# Generated by Django 5.2.8 on 2025-12-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_trainingcompletion_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcompletion',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
