# Generated by Django 5.2.8 on 2025-12-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_trainingcompletion_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hr_contact_name',
            field=models.CharField(blank=True, default='HR Team', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='hr_email',
            field=models.EmailField(blank=True, help_text='Default FROM email for HR communications', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
