# Generated by Django 5.2.8 on 2025-12-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_organization_hr_contact_name_organization_hr_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='hr_contact_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='hr_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
    ]
