# Generated by Django 5.2.8 on 2025-12-26 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_remove_organization_hr_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('hr_email', models.EmailField(blank=True, help_text='Default FROM email for offer letters', max_length=254)),
                ('hr_contact_name', models.CharField(blank=True, default='HR Team', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Branding',
                'verbose_name_plural': 'Organization Branding',
            },
        ),
    ]
