# Generated by Django 6.0 on 2026-01-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_alter_organizationuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR Manager', 'HR Manager'), ('Employee', 'Employee'), ('MD', 'MD'), ('Team Lead', 'Team Lead'), ('Manager', 'Manager'), ('Accounts Manager', 'Accounts Manager')], max_length=50),
        ),
    ]
