# Generated by Django 6.0 on 2026-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_alter_organizationuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='crm_activity_timeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_advanced_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_duplicate_lead_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_kanban_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_lead_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_pdf_quotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='crm_whatsapp_button',
            field=models.BooleanField(default=False),
        ),
    ]
