# Generated by Django 6.0 on 2026-06-16 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_organization_crm_activity_timeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='crm_activity_timeline',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='crm_advanced_reports',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='crm_duplicate_lead_check',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='crm_kanban_pipeline',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='crm_lead_scoring',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='crm_pdf_quotation',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='crm_whatsapp_button',
        ),
        migrations.CreateModel(
            name='OrganizationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_whatsapp_button', models.BooleanField(default=False)),
                ('crm_kanban_pipeline', models.BooleanField(default=False)),
                ('crm_lead_scoring', models.BooleanField(default=False)),
                ('crm_activity_timeline', models.BooleanField(default=False)),
                ('crm_advanced_reports', models.BooleanField(default=False)),
                ('crm_duplicate_lead_check', models.BooleanField(default=False)),
                ('crm_pdf_quotation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='organizations.organization')),
            ],
        ),
    ]
