# Generated by Django 6.0 on 2026-06-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_remove_organization_crm_activity_timeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationfeature',
            name='crm_direct_customer_conversion',
            field=models.BooleanField(default=False),
        ),
    ]
